{ config, helpers, lib, pkgs, ... }:

with lib;
let 
    cc = config.control;
    cfg = cc.homepage;
    settingsFormat = pkgs.formats.yaml { };

    # collect all (enabled) web-services
    webservices =
        (filter helpers.isEnabledNamedWebModule (
            helpers.modulesListWithNames config.control
        ));

    mkDefaultWidget = name: module: {
            name = {
                type = name;
                url = "${module.subdomain}.${cc.routing.domain}";
            };
        };
in {
  options.control.homepage = (helpers.webServiceDefaults {
    name = "Homepage";
    version = "-not a container-";
    subdomain = "homepage";
    port = 10012;
  }) // {
    paths = {
      default = helpers.mkInheritedPathOption {
        parentName = "home server global default path";
        parent = cc.defaultPath;
        defaultSubpath = "homepage";
        description = "Root path for Homepage media and appdata";
      };

      config = helpers.mkInheritedPathOption {
        parentName = "paths.default";
        parent = cfg.paths.default;
        defaultSubpath = "config";
        description = "Path for Homepage appdata (config).";
      };
    };

    generateConfig = mkOption {
      type = types.bool;
      default = true;
      description = ''
        Auto-generates config based on enabled Control modules.
      '';
    };

    additionalWidgets = mkOption {
        inherit (settingsFormat) type;
        default = [ ];
        description = ''
            Homepage bookmarks configuration to add to the configuration
            generated by Control.

            See <https://gethomepage.dev/configs/bookmarks/>.
            '';
        example = ''
            [{
                resources = {
                    cpu = true;
                    disk = "/";
                    memory = true;
                };
            }]
        '';
    };
  };

  config = mkIf cfg.enable {
    services.homepage-dashboard.enable = true;
    services.homepage-dashboard.listenPort = cfg.port;
    services.homepage-dashboard.allowedHosts = "${cfg.subdomain}.${cc.routing.domain}";
    services.homepage-dashboard.widgets = 
        (forEach webservices (m: mkDefaultWidget m.name m.module)) ++ cfg.additionalWidgets;
  };
}
